version: "3.9"

services:
  backend-node:
    image: ghcr.io/danielxfeng/web-backend-node:latest
    container_name: web_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - ./.key:/app/.key
    depends_on:
      - meilisearch
    networks:
      - web_net
    command: sh -c "npx prisma migrate deploy && npm run start"

  meilisearch:
    image: getmeili/meilisearch:v1.24
    restart: always
    env_file:
      - .env.production
    expose:
      - "7700"
    networks:
      - web_net

networks:
  web_net:
#docker network connect website_default web_backend
