services:
  postgres:
    image: postgres:17
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: blog_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - web_net
    depends_on:
      - postgres

  #  elasticsearch:
  #    image: elasticsearch:9.0.1
  #    container_name: blog_elasticsearch
  #    restart: always
  #    environment:
  #      discovery.type: single-node
  #      xpack.security.enabled: false
  #    ports:
  #      - "9200:9200"
  #    volumes:
  #      - esdata:/usr/share/elasticsearch/data
  #    networks:
  #      - web_net

  meilisearch:
    image: getmeili/meilisearch:v1.18
    container_name: blog_meilisearch
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - web_net

volumes:
  pgdata:
  esdata:
  meilisearch_data:

networks:
  web_net:
